### ISSUE TITLE
problem on executing notebook after installation

### ISSUE THREAD

**Issue by mdforti** [srmnitc/pyiron-apt#2]
I am making a fresh install of paraprobe and composition space from conda with this command:

conda create -p /<path-to>AnacondaEnvironments/paraprove-compositionspace -c conda-forge paraprobe compositionspace

then, I try to execute this notebook:

https://github.com/srmnitc/pyiron-apt/blob/main/paraprobe/workflow_paraprobe.ipynb

I get the same error as in the linked one, regarding missing jupyterlab_h5web, which works after installing manually with pip.

Then I get errors regarding missing modules:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from paraprobe_parmsetup.tools.transcoder_guru import ParmsetupTranscoder
      2 from paraprobe_parmsetup.tools.ranger_guru import ParmsetupRanger
      3 from paraprobe_parmsetup.tools.surfacer_guru import ParmsetupSurfacer

File /scratch/AnacondaEnvironments/paraprove-compositionspace/lib/python3.10/site-packages/paraprobe_parmsetup/tools/transcoder_guru.py:10
      1 """
      2 //##MK::GPLV3.
      3 
      4 Python class to be used in Jupyter notebooks for creating
      5 HDF5 configuration files for paraprobe-transcoder
      6 """
      8 import numpy as np
---> 10 from paraprobe_parmsetup.utils.numerics import TOOLS_IN_TOOLBOX
     12 from paraprobe_parmsetup.utils.hashing import get_file_hashvalue
     14 from paraprobe_parmsetup.utils.nodeinfo import NodeInfo

ModuleNotFoundError: No module named 'paraprobe_parmsetup.utils'

---------------------------------------------------------------------------

which is solved by modifying the pointed lines to:

```
from paraprobe_parmsetup.tools.utils.numerics import TOOLS_IN_TOOLBOX
```

is this a versioning problem or should I make an issue in paraprobe gitlab ?

Best regards,

**Comment by srmnitc** [comment]
This should be fixed in the latest release of paraprobe.

**Comment by srmnitc** [comment]
I can confirm this has been fixed in the latest conda release

**Comment by mdforti** [comment]
this is partially fixed:

jupyterlab_h5web needs to be installed manually using pip 

pyiron needs to be installed manually using conda from conda-forge.


but then trying to use the notebook:

https://github.com/mdforti/pyiron-apt/blob/failing_run/paraprobe_pyiron/workflow_paraprobe_pyiron.ipynb

fails with the shown error, probably due to missing config?

**Comment by srmnitc** [comment]
I had not pushed some local commits, should be okay now.
